package com.example.neatnest

import android.content.Context
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import androidx.core.content.FileProvider
import com.example.neatnest.data.model.DeviceSnapshot
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

// generates a PDF report from device stats
class ReportGenerator(private val context: Context) {

    fun generateReport(snapshot: DeviceSnapshot?): Uri? {
        if (snapshot == null) return null

        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
        val page = doc.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply { textSize = 24f; color = Color.parseColor("#6A1B9A"); isFakeBoldText = true }
        val headerPaint = Paint().apply { textSize = 16f; color = Color.parseColor("#7B1FA2"); isFakeBoldText = true }
        val textPaint = Paint().apply { textSize = 13f; color = Color.parseColor("#333333") }
        val subtextPaint = Paint().apply { textSize = 11f; color = Color.parseColor("#666666") }
        val linePaint = Paint().apply { color = Color.parseColor("#E1BEE7"); strokeWidth = 1f }

        var y = 50f
        val lm = 40f // left margin

        // title
        canvas.drawText("NeatNest Device Report", lm, y, titlePaint)
        y += 20f
        val dateStr = SimpleDateFormat("dd MMM yyyy, HH:mm:ss", Locale.getDefault()).format(Date())
        canvas.drawText("Generated: $dateStr", lm, y, subtextPaint)
        y += 30f
        canvas.drawLine(lm, y, 555f, y, linePaint)
        y += 25f

        // device info
        canvas.drawText("Device Information", lm, y, headerPaint)
        y += 22f
        canvas.drawText("Model: ${Build.MANUFACTURER} ${Build.MODEL}", lm, y, textPaint)
        y += 18f
        canvas.drawText("Android: ${Build.VERSION.RELEASE} (SDK ${Build.VERSION.SDK_INT})", lm, y, textPaint)
        y += 18f
        canvas.drawText("Board: ${Build.BOARD} | Hardware: ${Build.HARDWARE}", lm, y, textPaint)
        y += 30f
        canvas.drawLine(lm, y, 555f, y, linePaint)
        y += 25f

        // RAM
        canvas.drawText("RAM", lm, y, headerPaint)
        y += 22f
        val ramUsed = snapshot.ramTotalMb - snapshot.ramAvailableMb
        val ramPct = if (snapshot.ramTotalMb > 0) ramUsed * 100 / snapshot.ramTotalMb else 0
        canvas.drawText("Used: $ramUsed MB / ${snapshot.ramTotalMb} MB ($ramPct%)", lm, y, textPaint)
        y += 18f
        canvas.drawText("Available: ${snapshot.ramAvailableMb} MB", lm, y, textPaint)
        y += 30f
        canvas.drawLine(lm, y, 555f, y, linePaint)
        y += 25f

        // storage
        canvas.drawText("Storage", lm, y, headerPaint)
        y += 22f
        val storageUsedGb = (snapshot.storageTotalMb - snapshot.storageAvailableMb) / 1024f
        val storageTotalGb = snapshot.storageTotalMb / 1024f
        val storageAvailGb = snapshot.storageAvailableMb / 1024f
        canvas.drawText("Used: %.1f GB / %.1f GB".format(storageUsedGb, storageTotalGb), lm, y, textPaint)
        y += 18f
        canvas.drawText("Available: %.1f GB".format(storageAvailGb), lm, y, textPaint)
        y += 30f
        canvas.drawLine(lm, y, 555f, y, linePaint)
        y += 25f

        // battery
        canvas.drawText("Battery", lm, y, headerPaint)
        y += 22f
        canvas.drawText("Level: ${snapshot.batteryLevel}%", lm, y, textPaint)
        y += 18f
        canvas.drawText("Temperature: %.1f°C".format(snapshot.batteryTemperature), lm, y, textPaint)
        y += 18f
        canvas.drawText("Charging: ${if (snapshot.isCharging) "Yes" else "No"}", lm, y, textPaint)
        y += 30f
        canvas.drawLine(lm, y, 555f, y, linePaint)
        y += 25f

        // CPU
        canvas.drawText("CPU", lm, y, headerPaint)
        y += 22f
        canvas.drawText("Usage: %.1f%%".format(snapshot.cpuUsagePercent), lm, y, textPaint)
        y += 40f

        // footer
        canvas.drawLine(lm, y, 555f, y, linePaint)
        y += 20f
        canvas.drawText("Report generated by NeatNest v2.1.5.1", lm, y, subtextPaint)

        doc.finishPage(page)

        // save to cache dir
        val reportsDir = File(context.cacheDir, "reports")
        reportsDir.mkdirs()
        val file = File(reportsDir, "device_report_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()

        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    }
}
